name: Your-Awesome-App

# Configs

configs:
  Debug: debug
  Release: release
  Internal: internal

# Options

options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    # macOS: 12.0
    iOS: 15.0
  bundleIdPrefix: com.your-org-name
  
# Attributes

attributes:
  ORGANIZATIONNAME: Your-Org-Name

# Targets

targets:
  iOS:
    type: application
    platform: iOS
    sources: 
      - path: Main/Shared
      - path: Main/Resources
      - path: Main/iOS
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
      Internal: Configs/Internal.xcconfig
    # scheme:
    #   testTargets:
    #   - UnitTests
    postCompileScripts:
      - name: SwiftLint
        script: |
                swiftlint --config .swiftlint.yml
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)$(SCHEME_NAME)
    configs:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)$(SCHEME_NAME)
        PRODUCT_NAME: $(APP_NAME)$(SCHEME_NAME)
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        INFOPLIST_FILE: Main/iOS/Info.plist
      # Debug:
      #   CODE_SIGN_STYLE: Automatic
      #   CODE_SIGN_IDENTITY: "Apple Development"
      # Internal:
      #   CODE_SIGN_STYLE: Automatic
      #   CODE_SIGN_IDENTITY: "Apple Distribution"
      # Release:
      #   CODE_SIGN_STYLE: Automatic
      #   CODE_SIGN_IDENTITY: "Apple Distribution"
      
  # UnitTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources:
  #     - path: Main/Tests
